# This file is used by the Thunderstore CLI to build and publish your mod to Thunderstore. https://github.com/thunderstore-io/thunderstore-cli

[config]
schemaVersion = "0.0.1"

[package]
namespace = "Zozokasu" # TODO: Change this to the team you're uploading the mod to on Thunderstore
name = "ResoniteSpout" # Change this to your mod's name, no spaces or special characters, max 128 characters
versionNumber = "1.0.4" # Uncomment this if publishing via manual tcli! Change this to your mod's version, must be in semantic versioning format (e.g. 1.0.0, 2.1.3, 0.1.0-alpha.1)
description = "A resonite mod that enables real-time camera output streaming via Spout." # TODO: Change this to your mod's description, max 250 characters
websiteUrl = "https://github.com/Zozokasu/ResoniteSpout" # TODO: Change this to your mod's website/repository, or leave blank
containsNsfwContent = false

# List any dependencies your mod has here, in the format "namespace-modname" = "version-constraint"
[package.dependencies] 
Nytra-InterprocessLib = "2.0.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

# Copy the compiled DLL to the plugins folder in the mod package
[[build.copy]]
source = "./out/ResoniteSpout.Engine.dll"
target = "plugins/ResoniteSpout.Engine/"


[[build.copy]]
source = "./out/ResoniteSpout.Renderer.dll"
target = "Renderer/BepInEx/Plugins/ResoniteSpout.Renderer/"

[[build.copy]]
source = "./libs/KlakSpout.dll"
target = "Renderer/BepInEx/Plugins/ResoniteSpout.Renderer/"

# Uncomment the following lines to include CHANGELOG file in your mod package. https://wiki.thunderstore.io/mods/updating-a-package#changelog
# [[build.copy]]
# source = "./CHANGELOG.md"
# target = "/"

# Uncomment the following line to include LICENSE file in your mod package, if you have one.
[[build.copy]]
source = "./LICENSE"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["resonite"]

[publish.categories]
resonite = [ "Tools" ]
